/**
 * Reusable presentational components for the GP Portal page.
 *
 * v2.0 — Premium gold/white design system, enhanced micro-interactions,
 * improved mobile-first layout, and refined visual hierarchy.
 */
import { useEffect, useState, useCallback } from "react";
import {
  Star, Eye, Scissors, TrendingUp, TrendingDown, Info, ChevronLeft, ChevronRight,
  Target, Calendar, Clock, AlertTriangle, ThumbsUp, Flame, Crown, Sparkles, Zap,
  Wand2, RefreshCw, ChevronDown, ChevronUp,
} from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { Area, AreaChart, ResponsiveContainer } from "recharts";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { MONTH_NAMES } from "../../../../shared/const";

// ============================================================================
// AI Coach card — personalised LLM summary block
// ============================================================================

export function AICoachCard({
  insights,
  isLoading,
  isFetching,
  onRefresh,
  generatedAt,
  cached,
}: {
  insights: { headline: string; strength: string; focus: string; motivation: string } | null | undefined;
  isLoading: boolean;
  isFetching: boolean;
  onRefresh: () => void;
  generatedAt?: Date | string | null;
  cached?: boolean;
}) {
  const [collapsed, setCollapsed] = useState(false);
  const generatedLabel = generatedAt
    ? new Date(generatedAt).toLocaleString(undefined, { hour: "2-digit", minute: "2-digit", month: "short", day: "numeric" })
    : null;

  return (
    <section className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm hover:shadow transition-shadow duration-300">
      {/* One restrained corner accent — same family as the hero,
          replaces the previous ambient-glow soup. */}
      <div className="pointer-events-none absolute -top-12 -right-12 h-36 w-36 rounded-full bg-amber-100/40 blur-2xl" aria-hidden />

      <div className="relative p-5 sm:p-6">
        <div className="flex items-start justify-between gap-3 mb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-amber-50 border border-amber-200">
              <Wand2 className="h-4 w-4 text-amber-600" />
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-[0.18em] font-semibold text-slate-500">AI Coach</p>
              <h3 className="text-base font-semibold text-slate-900 leading-tight mt-0.5">
                {isLoading ? "Reading your evaluations…" : insights?.headline || "Your personalised summary"}
              </h3>
            </div>
          </div>
          <div className="flex items-center gap-0.5">
            <button
              onClick={onRefresh}
              disabled={isFetching}
              className="p-1.5 rounded-lg hover:bg-slate-100 transition-colors disabled:opacity-50"
              aria-label="Regenerate insights"
              title="Regenerate insights"
            >
              <RefreshCw className={`h-3.5 w-3.5 text-slate-500 ${isFetching ? "animate-spin" : ""}`} />
            </button>
            <button
              onClick={() => setCollapsed(c => !c)}
              className="p-1.5 rounded-lg hover:bg-slate-100 transition-colors"
              aria-label={collapsed ? "Expand" : "Collapse"}
            >
              {collapsed ? <ChevronDown className="h-3.5 w-3.5 text-slate-500" /> : <ChevronUp className="h-3.5 w-3.5 text-slate-500" />}
            </button>
          </div>
        </div>

        {!collapsed && (
          <div className="space-y-2.5">
            {isLoading || !insights ? (
              <>
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
                <Skeleton className="h-4 w-4/6" />
              </>
            ) : (
              <>
                <CoachLine icon={Sparkles} tone="emerald" label="Strength" text={insights.strength} />
                <CoachLine icon={Target} tone="gold" label="Focus next" text={insights.focus} />
                <CoachLine icon={Flame} tone="amber" label="Keep going" text={insights.motivation} />
              </>
            )}
          </div>
        )}

        <div className="mt-4 flex items-center justify-between text-[10px] text-slate-400">
          <span>Generated by AI from your last evaluations · not a manual review</span>
          {generatedLabel && (
            <span>{cached ? "Updated" : "Just generated"} · {generatedLabel}</span>
          )}
        </div>
      </div>
    </section>
  );
}

function CoachLine({ icon: Icon, tone, label, text }: {
  icon: typeof Sparkles; tone: "emerald" | "gold" | "amber"; label: string; text: string;
}) {
  const palette =
    tone === "emerald" ? "bg-emerald-100 text-emerald-700 border-emerald-200" :
    tone === "gold" ? "bg-amber-100 text-amber-800 border-amber-300" :
    "bg-yellow-100 text-yellow-800 border-yellow-300";
  return (
    <div className="flex items-start gap-3">
      <div className={`mt-0.5 shrink-0 inline-flex items-center gap-1 px-2 py-0.5 rounded-full border text-[10px] font-semibold uppercase tracking-wide ${palette}`}>
        <Icon className="h-3 w-3" />
        {label}
      </div>
      <p className="text-sm text-slate-700 leading-relaxed">{text}</p>
    </div>
  );
}

// ============================================================================
// Performance Pulse hero — dramatic full-width hero block
// ============================================================================

function useCountUp(target: number, durationMs = 900): number {
  const [val, setVal] = useState(0);
  useEffect(() => {
    let frame: number;
    const start = performance.now();
    const tick = (t: number) => {
      const k = Math.min(1, (t - start) / durationMs);
      const eased = 1 - Math.pow(1 - k, 3); // ease-out cubic
      setVal(target * eased);
      if (k < 1) frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [target, durationMs]);
  return val;
}

export function PerformancePulseHero({
  gpFirstName,
  greeting,
  avgScore,
  maxScore,
  avgAppearance,
  maxAppearance,
  avgGamePerf,
  maxGamePerf,
  evaluationsCount,
  tierName,
  tierAccent,
  TierIcon,
  delta,
  deltaLabel,
  cleanStreak,
  lastEvaluationDate,
  nextTier,
  availableMonths,
  selectedMonth,
  selectedYear,
  onMonthChange,
}: {
  gpFirstName: string;
  greeting: string;
  avgScore: number;
  maxScore: number;
  /** Optional sub-scores. When provided, the hero renders three
   *  Apple-Watch-style concentric rings (Overall · Appearance · Game)
   *  instead of a single pulse ring. */
  avgAppearance?: number;
  maxAppearance?: number;
  avgGamePerf?: number;
  maxGamePerf?: number;
  evaluationsCount: number;
  tierName: string;
  tierAccent: string;
  TierIcon: typeof Star;
  delta: number | null;
  deltaLabel: string | null;
  cleanStreak: number;
  lastEvaluationDate: Date | null;
  /** Optional tier-progress hint, e.g. { nextName: "Pro", pointsAway: 1.4 }.
   *  When set, surfaces "1.4 pts → Pro" so the GP has a concrete next
   *  goal anchored to the same tier vocabulary as the badge inside the
   *  ring. Pass `null` when already top-tier. */
  nextTier?: { nextName: string; pointsAway: number } | null;
  /** Month selector — when provided, renders a compact month picker
   *  inline with the hero so GPs can switch months without scrolling. */
  availableMonths?: Array<{ month: number; year: number; label: string; evalCount: number }>;
  selectedMonth?: number;
  selectedYear?: number;
  onMonthChange?: (month: number, year: number) => void;
}) {
  const animated = useCountUp(avgScore, 900);
  const overallPct = maxScore > 0 ? Math.min(100, Math.max(0, (avgScore / maxScore) * 100)) : 0;

  // Animate bars from 0% → target on mount / data change
  const [barMounted, setBarMounted] = useState(false);
  useEffect(() => {
    const id = requestAnimationFrame(() => setBarMounted(true));
    return () => { cancelAnimationFrame(id); setBarMounted(false); };
  }, [avgScore, avgAppearance, avgGamePerf]);
  const appearancePct = (avgAppearance != null && maxAppearance && maxAppearance > 0)
    ? Math.min(100, Math.max(0, (avgAppearance / maxAppearance) * 100))
    : null;
  const gamePerfPct = (avgGamePerf != null && maxGamePerf && maxGamePerf > 0)
    ? Math.min(100, Math.max(0, (avgGamePerf / maxGamePerf) * 100))
    : null;
  const showSubScores = appearancePct != null && gamePerfPct != null;

  return (
    <section className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white">
      {/* Single warm corner glow — the only decorative element. */}
      <div className="pointer-events-none absolute -top-32 -right-24 h-72 w-72 rounded-full bg-gradient-to-br from-amber-100/70 to-yellow-50/0 blur-3xl" aria-hidden />
      {/* Hairline accent at top — one line, not five. */}
      <div className="pointer-events-none absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-amber-300/50 to-transparent" aria-hidden />

      <div className="relative p-7 sm:p-9">
        {/* Header row — greeting + tier chip pinned right. Reads as
            metadata above the headline, not a decorated banner. */}
        <div className="flex items-start justify-between gap-3 mb-5">
          <p className="text-[11px] text-slate-500 uppercase tracking-[0.2em] font-semibold">{greeting}</p>
          <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-semibold uppercase tracking-widest bg-gradient-to-br ${tierAccent} text-white shrink-0`}>
            <TierIcon className="h-3 w-3" />
            {tierName}
          </span>
        </div>

        {/* Name */}
        <h1 className="text-3xl sm:text-5xl font-bold text-slate-900 leading-[1.1] tracking-tight">
          {gpFirstName}'s pulse
        </h1>
        <p className="text-sm text-slate-500 mt-2">
          {evaluationsCount} evaluation{evaluationsCount !== 1 ? "s" : ""} on record · keep stacking the wins
        </p>

        {/* Primary metric — score, max, delta, all in one elegant
            line. The big number anchors the hero without a giant
            ring stealing real estate. Wrapped in a transition container
            that fades/slides when the month changes. */}
        <div
          key={`${selectedMonth}-${selectedYear}`}
          className="mt-7 flex flex-col sm:flex-row sm:items-end gap-x-6 gap-y-3 sm:flex-wrap animate-in fade-in-0 slide-in-from-bottom-2 duration-300">
          <div className="flex items-baseline gap-2">
            <span className="text-6xl sm:text-7xl font-bold text-slate-900 tabular-nums leading-none tracking-tight">
              {animated.toFixed(1)}
            </span>
            <span className="text-2xl text-slate-300 font-light leading-none">/ {maxScore}</span>
          </div>
          <div className="flex items-center gap-2 flex-wrap pb-1">
            {delta !== null && (
              <span className={`inline-flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded-full border ${
                delta >= 0
                  ? "border-emerald-200 bg-emerald-50/70 text-emerald-700"
                  : "border-rose-200 bg-rose-50/70 text-rose-700"
              }`}>
                {delta >= 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                {delta >= 0 ? "+" : ""}{delta.toFixed(1)} {deltaLabel ? `vs ${deltaLabel}` : ""}
              </span>
            )}
            {nextTier && (
              <span className="inline-flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded-full border border-amber-200 bg-amber-50/70 text-amber-700">
                <Target className="h-3 w-3" />
                {nextTier.pointsAway.toFixed(1)} to {nextTier.nextName}
              </span>
            )}
            {cleanStreak >= 2 && (
              <span className="inline-flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded-full border border-amber-200 bg-amber-50/70 text-amber-700">
                {cleanStreak >= 5 ? <Crown className="h-3 w-3" /> : <Flame className="h-3 w-3" />}
                {cleanStreak} clean in a row
              </span>
            )}
          </div>
        </div>

        {/* Primary progress bar — horizontal, takes the full width.
            Replaces the ring as the visual reference for "where am I". */}
        <div className="mt-5">
          <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
            <div
              className="h-full rounded-full bg-gradient-to-r from-amber-400 to-orange-500 transition-[width] duration-1000 ease-out"
              style={{ width: barMounted ? `${overallPct}%` : '0%' }}
            />
          </div>
          <div className="mt-1.5 flex items-center justify-between text-[11px] text-slate-400 font-medium tabular-nums">
            <span>{overallPct.toFixed(0)}% of max</span>
            {lastEvaluationDate && (
              <span className="inline-flex items-center gap-1 text-slate-500">
                <Zap className="h-3 w-3 text-amber-500" />
                Last eval {formatDistanceToNow(lastEvaluationDate, { addSuffix: true })}
              </span>
            )}
          </div>
        </div>

        {/* Month selector — compact inline picker so GPs can switch
            the viewed month directly from the hero card. */}
        {availableMonths && availableMonths.length > 0 && onMonthChange && (
          <div className="mt-5 flex items-center gap-2 flex-wrap">
            <span className="text-[11px] uppercase tracking-[0.14em] text-slate-400 font-semibold mr-1">Month</span>
            {availableMonths.map(m => {
              const isActive = m.month === selectedMonth && m.year === selectedYear;
              return (
                <button
                  key={`${m.year}-${m.month}`}
                  onClick={() => onMonthChange(m.month, m.year)}
                  disabled={m.evalCount === 0}
                  className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all duration-200 border ${
                    isActive
                      ? 'bg-gradient-to-br from-amber-500 to-yellow-500 text-white border-amber-400 shadow-sm shadow-amber-200/50'
                      : m.evalCount > 0
                        ? 'bg-white border-slate-200 text-slate-600 hover:border-amber-300 hover:bg-amber-50/50'
                        : 'bg-slate-50 border-slate-100 text-slate-300 cursor-not-allowed'
                  }`}
                >
                  {m.label}
                </button>
              );
            })}
          </div>
        )}

        {/* Sub-scores — two clean rows, each with label + value + slim
            colored bar. No more concentric ring soup. */}
        {showSubScores && (
          <div key={`sub-${selectedMonth}-${selectedYear}`} className="mt-7 pt-5 border-t border-slate-100 grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-4 animate-in fade-in-0 slide-in-from-bottom-1 duration-500">
            {[
              { key: "appearance", label: "Appearance", value: avgAppearance!, max: maxAppearance!, pct: appearancePct!, color: "#10b981", bg: "bg-emerald-500" },
              { key: "game", label: "Game performance", value: avgGamePerf!, max: maxGamePerf!, pct: gamePerfPct!, color: "#3b82f6", bg: "bg-blue-500" },
            ].map(s => (
              <div key={s.key}>
                <div className="flex items-baseline justify-between gap-2">
                  <span className="inline-flex items-center gap-2 text-[11px] uppercase tracking-[0.14em] text-slate-500 font-semibold">
                    <span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: s.color }} aria-hidden />
                    {s.label}
                  </span>
                  <span className="text-sm font-semibold text-slate-800 tabular-nums">
                    {s.value.toFixed(1)}<span className="text-slate-400 font-normal"> / {s.max}</span>
                  </span>
                </div>
                <div className="mt-2 h-1 bg-slate-100 rounded-full overflow-hidden">
                  <div
                    className={`h-full rounded-full ${s.bg} transition-[width] duration-1000 ease-out`}
                    style={{
                      width: barMounted ? `${s.pct}%` : '0%',
                      transitionDelay: s.key === 'appearance' ? '200ms' : '400ms',
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

// ============================================================================
// Score card — large metric display with premium hover effects
// ============================================================================

export function ScoreCard({ score, maxScore, label, icon: Icon, accentColor, bgColor, tooltip, delta, trend, sparkColor }: {
  score: number; maxScore: number; label: string; icon: typeof Star; accentColor: string; bgColor: string; tooltip?: string;
  delta?: number | null;
  trend?: Array<{ value: number }>;
  sparkColor?: string;
}) {
  const percentage = maxScore > 0 ? (score / maxScore) * 100 : 0;
  const [showTooltip, setShowTooltip] = useState(false);

  const getStatus = () => {
    if (percentage >= 90) return { text: 'Excellent', color: 'text-emerald-600', badge: 'bg-emerald-50 border-emerald-200 text-emerald-700' };
    if (percentage >= 80) return { text: 'Great', color: 'text-green-600', badge: 'bg-green-50 border-green-200 text-green-700' };
    if (percentage >= 70) return { text: 'Good', color: 'text-amber-600', badge: 'bg-amber-50 border-amber-200 text-amber-700' };
    return { text: 'Needs Work', color: 'text-red-600', badge: 'bg-red-50 border-red-200 text-red-700' };
  };
  const status = getStatus();
  const showDelta = typeof delta === "number" && delta !== 0;

  return (
    <div className={`relative overflow-hidden rounded-2xl bg-white p-5 sm:p-6 border border-slate-200 shadow-sm hover:shadow transition-shadow duration-300`}>
      <div className="relative z-10">
        <div className="flex items-center justify-between mb-5">
          <div className={`p-2 rounded-xl border ${accentColor}`}>
            <Icon className="h-4 w-4" />
          </div>
          <div className="flex items-center gap-2">
            {tooltip && (
              <div className="relative">
                <button
                  onClick={() => setShowTooltip(!showTooltip)}
                  className="p-1 rounded-full hover:bg-slate-100 transition-colors"
                  aria-label="Score formula"
                >
                  <Info className="h-3.5 w-3.5 text-slate-400" />
                </button>
                {showTooltip && (
                  <div className="absolute right-0 top-7 z-50 w-48 p-3 bg-white border border-slate-200 rounded-xl text-xs text-slate-600 shadow-md">
                    {tooltip}
                  </div>
                )}
              </div>
            )}
            <span className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded-full border ${status.badge}`}>{status.text}</span>
          </div>
        </div>
        <div className="mb-3">
          <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500 font-semibold">{label}</p>
          <div className="flex items-baseline gap-1.5 flex-wrap mt-1">
            <span className="text-4xl sm:text-[44px] font-bold text-slate-900 tabular-nums leading-none tracking-tight">{score.toFixed(1)}</span>
            <span className="text-lg text-slate-400 font-normal">/ {maxScore}</span>
            {showDelta && (
              <span className={`ml-1 inline-flex items-center gap-0.5 text-[11px] font-medium px-1.5 py-0.5 rounded-full ${
                (delta as number) > 0
                  ? "bg-emerald-50 text-emerald-700"
                  : "bg-rose-50 text-rose-700"
              }`}>
                {(delta as number) > 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                {(delta as number) > 0 ? "+" : ""}{(delta as number).toFixed(1)}
              </span>
            )}
          </div>
        </div>
        {/* Slim progress bar — single accent colour, no gradient
            soup. Width animates on first paint. */}
        <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
          <div
            className="h-full rounded-full transition-[width] duration-1000 ease-out"
            style={{ width: `${percentage}%`, backgroundColor: sparkColor || "#f59e0b" }}
          />
        </div>
        {trend && trend.length >= 2 && (() => {
          // SVG `id` attributes can't contain whitespace — when the
          // label has a space ("Overall Score", "Game Performance")
          // the `url(#spark-Overall Score)` reference becomes invalid
          // and the fill silently falls back to the default black
          // colour, producing the dirty grey smudge under the line.
          // Slugify the label so the gradient resolves cleanly.
          const slug = label.replace(/\s+/g, "-").toLowerCase();
          return (
            <div className="mt-3 h-10 -mx-1" aria-hidden>
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={trend} margin={{ top: 2, right: 2, left: 2, bottom: 0 }}>
                  <defs>
                    <linearGradient id={`spark-${slug}`} x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor={sparkColor || "#f59e0b"} stopOpacity={0.35} />
                      <stop offset="100%" stopColor={sparkColor || "#f59e0b"} stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <Area
                    type="monotone"
                    dataKey="value"
                    stroke={sparkColor || "#f59e0b"}
                    strokeWidth={2}
                    fill={`url(#spark-${slug})`}
                    isAnimationActive={false}
                    dot={false}
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          );
        })()}
      </div>
    </div>
  );
}

// ============================================================================
// Achievement badge — locked/unlocked tile
// ============================================================================

export function AchievementBadge({ icon: Icon, title, description, unlocked, color, progress, progressLabel, rarity }: {
  icon: typeof Star;
  title: string;
  description: string;
  unlocked: boolean;
  color: string;
  /** 0–1 progress to unlock. When set on a locked badge, a progress bar
   *  + percentage replace the dim grayscale state — turns "locked"
   *  badges into a visible goal instead of dead space. */
  progress?: number | null;
  /** Short progress hint, e.g. "3/5 evaluations" or "+1.2 to go". */
  progressLabel?: string | null;
  /** Visual hierarchy on the badge — common feels earned, legendary
   *  feels like a flex. Drives the rim/glow treatment when unlocked. */
  rarity?: "common" | "rare" | "epic" | "legendary";
}) {
  const showProgress = !unlocked && typeof progress === "number" && progress > 0;
  const almostThere = showProgress && (progress as number) >= 0.66;
  // Rarity rim — only visible on unlocked badges, layered as a thin
  // ring around the tile. Legendary gets a slowly-rotating conic
  // gradient so it reads as "rare prize" without being garish.
  const rarityRim =
    !unlocked || !rarity ? null :
    rarity === "legendary" ? "ring-2 ring-amber-400/60 shadow-md shadow-amber-200/60" :
    rarity === "epic" ? "ring-2 ring-amber-300/60 shadow-sm shadow-amber-200/40" :
    rarity === "rare" ? "ring-1 ring-amber-300/40" :
    null;
  const rarityLabel =
    !rarity ? null :
    rarity === "legendary" ? { text: "Legendary", cls: "text-amber-700 bg-gradient-to-r from-amber-100 to-yellow-100 border-amber-300" } :
    rarity === "epic" ? { text: "Epic", cls: "text-amber-700 bg-amber-50 border-amber-200" } :
    rarity === "rare" ? { text: "Rare", cls: "text-slate-600 bg-slate-50 border-slate-200" } :
    { text: "Common", cls: "text-slate-500 bg-slate-50 border-slate-200" };
  return (
    <div className={`relative p-4 rounded-xl border transition-all duration-300 group cursor-default ${
      unlocked
        ? `${color} shadow-sm hover:shadow-md hover:shadow-amber-100/60 hover:-translate-y-0.5 ${rarityRim ?? ""}`
        : showProgress
          ? `bg-white border-slate-200 shadow-sm hover:shadow-md hover:-translate-y-0.5 ${almostThere ? "ring-1 ring-amber-200/80" : ""}`
          : 'bg-slate-50 border-slate-200 opacity-60'
    }`}>
      {/* Legendary rotating rim — only on unlocked legendary badges.
          A super-slow conic gradient halo so they pop without being
          distracting. */}
      {unlocked && rarity === "legendary" && (
        <div className="absolute -inset-px rounded-xl opacity-30 group-hover:opacity-60 transition-opacity duration-300 pointer-events-none [background:conic-gradient(from_0deg,#fbbf24_0deg,#f59e0b_90deg,#f97316_180deg,#fbbf24_270deg,#f59e0b_360deg)] animate-[spin_8s_linear_infinite] blur-sm" aria-hidden />
      )}
      {/* Gold shimmer on hover for unlocked */}
      {unlocked && (
        <div className="absolute inset-0 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-gradient-to-br from-amber-50/40 to-transparent pointer-events-none" aria-hidden />
      )}
      {/* "Almost there" pulse halo */}
      {almostThere && (
        <div className="absolute inset-0 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-gradient-to-br from-amber-50/60 to-transparent pointer-events-none" aria-hidden />
      )}
      <div className="flex items-center gap-3 relative">
        <div className={`p-2.5 rounded-xl transition-all duration-300 ${
          unlocked
            ? 'bg-white/80 border border-amber-200/60 group-hover:scale-110 group-hover:border-amber-300'
            : showProgress
              ? `bg-amber-50 border ${almostThere ? "border-amber-300" : "border-amber-100"} group-hover:scale-110`
              : 'bg-slate-100 border border-transparent'
        }`}>
          <Icon className={`h-5 w-5 ${
            unlocked ? 'text-amber-700' : showProgress ? 'text-amber-500' : 'text-slate-400'
          }`} />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 flex-wrap">
            <p className={`font-semibold text-sm truncate ${
              unlocked ? 'text-slate-800' : showProgress ? 'text-slate-700' : 'text-slate-400'
            }`}>{title}</p>
            {rarityLabel && (
              <span className={`shrink-0 inline-flex items-center px-1.5 py-0 text-[9px] uppercase tracking-wider font-bold rounded-full border ${rarityLabel.cls}`}>
                {rarityLabel.text}
              </span>
            )}
          </div>
          <p className={`text-xs truncate ${
            unlocked ? 'text-slate-500' : showProgress ? 'text-slate-500' : 'text-slate-400'
          }`}>{description}</p>
          {showProgress && (
            <div className="mt-2 flex items-center gap-2">
              <div className="flex-1 h-1.5 rounded-full bg-slate-100 overflow-hidden">
                <div
                  className={`h-full rounded-full transition-[width] duration-700 ease-out ${
                    almostThere
                      ? "bg-gradient-to-r from-amber-400 to-yellow-500"
                      : "bg-gradient-to-r from-slate-300 to-amber-300"
                  }`}
                  style={{ width: `${Math.min(100, Math.max(4, (progress as number) * 100))}%` }}
                />
              </div>
              <span className={`text-[10px] font-semibold tabular-nums shrink-0 ${
                almostThere ? "text-amber-700" : "text-slate-500"
              }`}>
                {progressLabel ?? `${Math.round((progress as number) * 100)}%`}
              </span>
            </div>
          )}
        </div>
      </div>
      {unlocked && (
        <div className="absolute -top-1.5 -right-1.5 w-5 h-5 bg-gradient-to-br from-amber-400 to-yellow-500 rounded-full flex items-center justify-center shadow-sm shadow-amber-200/60">
          <span className="text-[10px] text-white font-bold">✓</span>
        </div>
      )}
    </div>
  );
}

// ============================================================================
// Stat card — compact metric tile with gold hover
// ============================================================================

export function StatCard({ icon: Icon, value, label, color, trend, hint, trendIsPositiveWhenDown }: {
  icon: typeof Eye;
  value: string | number;
  label: string;
  color: string;
  trend?: number;
  /** Short sub-line ("vs last month", "of 13 in team"). Replaces the
   *  empty caption space below the label so zero-stat cards aren't
   *  visually dead. */
  hint?: string | null;
  /** When true (e.g. for "Mistakes") a NEGATIVE trend is good and
   *  should render in green. Defaults to "up = good = green" semantics. */
  trendIsPositiveWhenDown?: boolean;
}) {
  // Decide trend tone from `trendIsPositiveWhenDown` so each card can
  // express its own "lower is better" vs "higher is better" intent.
  const trendIsGood =
    trend !== undefined && trend !== 0 && (trendIsPositiveWhenDown ? trend < 0 : trend > 0);
  return (
    <div className={`relative ${color} rounded-2xl border border-slate-200/80 overflow-hidden group hover:shadow-md hover:shadow-amber-100/40 hover:-translate-y-0.5 transition-all duration-300 cursor-default`}>
      {/* Gold shimmer on hover */}
      <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-gradient-to-br from-amber-50/40 to-transparent pointer-events-none" aria-hidden />
      <div className="p-4 sm:p-5 relative">
        <div className="flex items-center gap-3 sm:gap-4 relative">
          <div className="bg-white/90 p-2.5 sm:p-3 rounded-xl shrink-0 shadow-sm border border-amber-100/60 group-hover:scale-110 group-hover:border-amber-200 transition-all duration-300">
            <Icon className="h-5 w-5 sm:h-6 sm:w-6 text-amber-700" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <p className="text-2xl sm:text-3xl font-bold text-slate-900 leading-none">{value}</p>
              {trend !== undefined && trend !== 0 && (
                <div className={`flex items-center gap-0.5 text-[11px] font-semibold px-2 py-0.5 rounded-full ${
                  trendIsGood
                    ? 'text-emerald-700 bg-emerald-50 border border-emerald-200'
                    : 'text-rose-700 bg-rose-50 border border-rose-200'
                }`}>
                  {trend > 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                  <span>{trend > 0 ? '+' : ''}{trend.toFixed(1)}</span>
                </div>
              )}
            </div>
            <p className="text-xs sm:text-sm text-slate-500 truncate mt-0.5">{label}</p>
            {hint && (
              <p className="text-[11px] text-slate-400 truncate mt-0.5">{hint}</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// ============================================================================
// Labeled comment — used inside expanded evaluation detail rows
// ============================================================================

export function LabeledComment({ icon: Icon, label, comment, score, maxScore }: {
  icon: typeof Scissors; label: string; comment: string | null; score: number | null; maxScore: number;
}) {
  if (!comment) return null;
  return (
    <div className="p-3 bg-amber-50/50 rounded-lg border border-amber-100/80 hover:border-amber-200 transition-colors duration-200">
      <div className="flex items-center justify-between mb-1.5">
        <div className="flex items-center gap-2">
          <Icon className="h-3.5 w-3.5 text-amber-600" />
          <span className="text-xs font-medium text-slate-500">{label}</span>
        </div>
        {score !== null && (
          <span className={`text-xs font-bold ${
            (score / maxScore) >= 0.9 ? 'text-emerald-600' :
            (score / maxScore) >= 0.7 ? 'text-amber-600' : 'text-red-600'
          }`}>{score}/{maxScore}</span>
        )}
      </div>
      <p className="text-sm text-slate-700 leading-relaxed">{comment}</p>
    </div>
  );
}

// ============================================================================
// Month selector — back/forward arrows around the displayed month/year
// ============================================================================

export function MonthSelector({ selectedMonth, selectedYear, onChange }: {
  selectedMonth: number; selectedYear: number;
  onChange: (month: number, year: number) => void;
}) {
  const handlePrev = () => {
    if (selectedMonth === 1) {
      onChange(12, selectedYear - 1);
    } else {
      onChange(selectedMonth - 1, selectedYear);
    }
  };
  const handleNext = () => {
    const now = new Date();
    const nextMonth = selectedMonth === 12 ? 1 : selectedMonth + 1;
    const nextYear = selectedMonth === 12 ? selectedYear + 1 : selectedYear;
    if (nextYear > now.getFullYear() || (nextYear === now.getFullYear() && nextMonth > now.getMonth() + 1)) return;
    onChange(nextMonth, nextYear);
  };

  const now = new Date();
  const isCurrentMonth = selectedMonth === now.getMonth() + 1 && selectedYear === now.getFullYear();

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handlePrev}
        className="p-2 rounded-lg bg-white border border-slate-200 hover:bg-amber-50 hover:border-amber-200 transition-all duration-200 shadow-sm"
      >
        <ChevronLeft className="h-4 w-4 text-slate-600" />
      </button>
      <div className="px-4 py-2 rounded-xl bg-white border border-amber-200/60 min-w-[160px] text-center shadow-sm">
        <span className="text-sm font-medium text-slate-800">
          {MONTH_NAMES[selectedMonth - 1]} {selectedYear}
        </span>
      </div>
      <button
        onClick={handleNext}
        disabled={isCurrentMonth}
        className={`p-2 rounded-lg border transition-all duration-200 shadow-sm ${
          isCurrentMonth
            ? 'bg-slate-50 border-slate-100 cursor-not-allowed'
            : 'bg-white border-slate-200 hover:bg-amber-50 hover:border-amber-200'
        }`}
      >
        <ChevronRight className={`h-4 w-4 ${isCurrentMonth ? 'text-slate-300' : 'text-slate-600'}`} />
      </button>
    </div>
  );
}

// ============================================================================
// Action plan card — coaching items for the GP
// ============================================================================

const PLAN_CATEGORY_TONE: Record<string, string> = {
  appearance: "border-emerald-200 bg-emerald-50",
  performance: "border-amber-200 bg-amber-50",
  attitude: "border-pink-200 bg-pink-50",
  attendance: "border-blue-200 bg-blue-50",
  errors: "border-rose-200 bg-rose-50",
  general: "border-slate-200 bg-slate-50",
};

// ============================================================================
// Streak chip — gamification element
// ============================================================================

export function StreakChip({ days, label, tone = "amber" }: {
  days: number;
  label?: string;
  tone?: "amber" | "emerald" | "gold";
}) {
  if (days <= 0) return null;
  const palette =
    tone === "emerald" ? "bg-emerald-50 border-emerald-200 text-emerald-700" :
    tone === "gold" ? "bg-amber-50 border-amber-300 text-amber-800" :
    "bg-amber-50 border-amber-200 text-amber-700";
  const Icon = tone === "gold" ? Crown : Flame;
  const text = label ?? `${days}-day streak`;
  return (
    <span className={`inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full border shadow-sm ${palette}`}>
      <Icon className="h-3.5 w-3.5" />
      {text}
    </span>
  );
}

// ============================================================================
// Month tab header — prominent month navigation header
// ============================================================================

export function MonthTabHeader({ selectedMonth, selectedYear, onChange, evalCount, errorCount, attitudeScore }: {
  selectedMonth: number; selectedYear: number;
  onChange: (month: number, year: number) => void;
  evalCount: number;
  errorCount: number;
  attitudeScore: number;
}) {
  const handlePrev = () => {
    if (selectedMonth === 1) onChange(12, selectedYear - 1);
    else onChange(selectedMonth - 1, selectedYear);
  };
  const handleNext = () => {
    const now = new Date();
    const nextMonth = selectedMonth === 12 ? 1 : selectedMonth + 1;
    const nextYear = selectedMonth === 12 ? selectedYear + 1 : selectedYear;
    if (nextYear > now.getFullYear() || (nextYear === now.getFullYear() && nextMonth > now.getMonth() + 1)) return;
    onChange(nextMonth, nextYear);
  };
  const now = new Date();
  const isCurrentMonth = selectedMonth === now.getMonth() + 1 && selectedYear === now.getFullYear();
  const monthLabel = MONTH_NAMES[selectedMonth - 1];

  return (
    <div className="relative overflow-hidden rounded-2xl border border-amber-200/60 bg-gradient-to-br from-white to-amber-50/40 p-5 sm:p-6 shadow-sm">
      {/* Decorative gold shimmer */}
      <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-transparent via-amber-400/50 to-transparent" aria-hidden />
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-3">
          <button
            onClick={handlePrev}
            className="p-2 rounded-lg bg-white border border-slate-200 hover:bg-amber-50 hover:border-amber-200 transition-all duration-200 shadow-sm"
            aria-label="Previous month"
          >
            <ChevronLeft className="h-4 w-4 text-slate-600" />
          </button>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-amber-600/70 font-semibold">Viewing</p>
            <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 leading-tight">
              {monthLabel}{" "}
              <span className="text-slate-400 font-normal">{selectedYear}</span>
            </h2>
          </div>
          <button
            onClick={handleNext}
            disabled={isCurrentMonth}
            className={`p-2 rounded-lg border transition-all duration-200 shadow-sm ${
              isCurrentMonth ? 'bg-slate-50 border-slate-100 cursor-not-allowed' : 'bg-white border-slate-200 hover:bg-amber-50 hover:border-amber-200'
            }`}
            aria-label="Next month"
          >
            <ChevronRight className={`h-4 w-4 ${isCurrentMonth ? 'text-slate-300' : 'text-slate-600'}`} />
          </button>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <span className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full bg-amber-50 border border-amber-200 text-amber-700">
            <Eye className="h-3 w-3" /> {evalCount} eval{evalCount !== 1 ? 's' : ''}
          </span>
          <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full border ${
            errorCount > 0 ? 'bg-red-50 border-red-200 text-red-700' : 'bg-emerald-50 border-emerald-200 text-emerald-700'
          }`}>
            <AlertTriangle className="h-3 w-3" /> {errorCount} mistake{errorCount !== 1 ? 's' : ''}
          </span>
          <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full border ${
            attitudeScore >= 0 ? 'bg-emerald-50 border-emerald-200 text-emerald-700' : 'bg-rose-50 border-rose-200 text-rose-700'
          }`}>
            <ThumbsUp className="h-3 w-3" /> {attitudeScore > 0 ? '+' : ''}{attitudeScore} attitude
          </span>
        </div>
      </div>
    </div>
  );
}

// ============================================================================
// At-a-glance strip — 4 micro-stats below the hero
// ============================================================================

export function AtAGlanceStrip({
  evalCount, mistakes, attitude, lastEvaluationDate,
}: {
  evalCount: number;
  mistakes: number;
  attitude: number;
  lastEvaluationDate: Date | null;
}) {
  const recencyLabel = lastEvaluationDate
    ? formatDistanceToNow(lastEvaluationDate, { addSuffix: true })
    : "—";
  // Single neutral tile — distinguishes itself by the icon tint
  // alone, not the whole tile background. Reads as a clean
  // "card row" instead of four competing colour blocks.
  const tiles: Array<{ icon: typeof Eye; label: string; value: string | number; iconCls: string }> = [
    { icon: Eye, label: "Evaluations", value: evalCount, iconCls: "text-amber-600 bg-amber-50 border-amber-100" },
    { icon: AlertTriangle, label: "Mistakes", value: mistakes, iconCls: mistakes > 0 ? "text-rose-600 bg-rose-50 border-rose-100" : "text-emerald-600 bg-emerald-50 border-emerald-100" },
    { icon: ThumbsUp, label: "Attitude", value: attitude > 0 ? `+${attitude}` : `${attitude}`, iconCls: attitude > 0 ? "text-emerald-600 bg-emerald-50 border-emerald-100" : "text-slate-500 bg-slate-50 border-slate-100" },
    { icon: Clock, label: "Last eval", value: recencyLabel, iconCls: "text-slate-500 bg-slate-50 border-slate-100" },
  ];
  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
      {tiles.map(t => (
        <div
          key={t.label}
          className="rounded-xl border border-slate-200 bg-white p-3.5 sm:p-4 flex items-center gap-3 hover:shadow-sm transition-shadow duration-200"
        >
          <div className={`shrink-0 inline-flex items-center justify-center h-9 w-9 rounded-lg border ${t.iconCls}`}>
            <t.icon className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <p className="text-[10px] uppercase tracking-[0.14em] text-slate-400 font-semibold">{t.label}</p>
            <p className="text-lg sm:text-xl font-semibold text-slate-900 truncate leading-tight tabular-nums mt-0.5">{t.value}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

export function ActionPlanCard({ items }: { items: Array<{ id: number; title: string; description: string | null; category: string; priority: string; status: string; dueDate: Date | null; source: string }> }) {
  const open = items.filter(i => i.status === "open");
  const inProgress = items.filter(i => i.status === "in_progress");
  return (
    <Card className="bg-white border-amber-200/60 shadow-sm hover:shadow-md transition-shadow duration-300">
      <CardHeader className="pb-3">
        <CardTitle className="text-slate-800 text-base flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-amber-100 border border-amber-200">
            <Target className="h-4 w-4 text-amber-700" />
          </div>
          Your action plan
        </CardTitle>
        <CardDescription className="text-slate-500 text-xs">
          {open.length} open, {inProgress.length} in progress — what your FM is asking you to focus on
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-2">
        {[...inProgress, ...open].slice(0, 6).map(item => (
          <div
            key={item.id}
            className={`border rounded-lg p-3 hover:shadow-sm transition-all duration-200 ${PLAN_CATEGORY_TONE[item.category] ?? "border-slate-200 bg-white"}`}
          >
            <div className="flex items-start justify-between gap-2 mb-1">
              <p className="text-sm font-semibold text-slate-800">{item.title}</p>
              <div className="flex items-center gap-1 shrink-0">
                <span className="text-[10px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 capitalize">{item.category}</span>
                {item.status === "in_progress" && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-amber-100 border border-amber-300 text-amber-700">In progress</span>
                )}
              </div>
            </div>
            {item.description && (
              <p className="text-xs text-slate-600 leading-relaxed">{item.description}</p>
            )}
            {item.dueDate && (
              <p className="text-[11px] text-slate-500 mt-1.5 inline-flex items-center gap-1">
                <Calendar className="h-2.5 w-2.5" />
                Due {new Date(item.dueDate).toLocaleDateString()}
              </p>
            )}
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

// ============================================================================
// Skeleton — layout-matching placeholder with shimmer
// ============================================================================

export function GPPortalSkeleton() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50/30 via-white to-yellow-50/20">
      <header className="border-b border-amber-200/40 bg-white/90 backdrop-blur-sm sticky top-0 z-10">
        <div className="container py-4 sm:py-5 flex items-center justify-between">
          <div className="flex items-center gap-3 sm:gap-4">
            <Skeleton className="h-12 w-12 sm:h-14 sm:w-14 rounded-2xl" />
            <div className="space-y-2">
              <Skeleton className="h-5 w-40" />
              <Skeleton className="h-3 w-28" />
            </div>
          </div>
          <Skeleton className="h-8 w-8 rounded-md" />
        </div>
      </header>
      <main className="container py-6 sm:py-8 space-y-8">
        {/* Hero block */}
        <Skeleton className="h-48 w-full rounded-3xl" />

        {/* At-a-glance strip */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-16 rounded-xl" />
          ))}
        </div>

        {/* 3 score cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-5">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-44 rounded-2xl" />
          ))}
        </div>

        {/* Tab strip placeholder */}
        <Skeleton className="h-10 w-full sm:w-96 rounded-lg" />

        {/* Body content placeholder */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Skeleton className="h-56 rounded-xl" />
          <Skeleton className="h-56 rounded-xl" />
        </div>
      </main>
    </div>
  );
}
